// Generates supabase/seed.sql from the TypeScript source of truth so the seed
// can never drift from lib/teams.ts + lib/players.ts.
// Run: npm run db:seed:gen
import { writeFileSync } from "node:fs";
import path from "node:path";
import { TEAMS } from "../lib/teams";
import { PLAYERS } from "../lib/players";
import { DEFAULT_SETTINGS } from "../lib/types";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

const teamRows = TEAMS.map(
  (t) =>
    `  (${q(t.code)}, ${q(t.name)}, ${q(t.flag)}, ${q(t.confederation)}, ${t.isLatam}, ${t.fifaSeed}, ${t.qualified})`,
).join(",\n");

const playerRows = PLAYERS.map(
  (p) => `  (${q(p.id)}, ${q(p.name)}, ${q(p.teamCode)})`,
).join(",\n");

const sql = `-- AUTO-GENERATED by scripts/gen-seed.ts — do not edit by hand.
-- Seeds reference data + default settings. Safe to re-run (upserts).

insert into teams (code, name, flag, confederation, is_latam, fifa_seed, qualified) values
${teamRows}
on conflict (code) do update set
  name = excluded.name, flag = excluded.flag, confederation = excluded.confederation,
  is_latam = excluded.is_latam, fifa_seed = excluded.fifa_seed, qualified = excluded.qualified;

insert into players (id, name, team_code) values
${playerRows}
on conflict (id) do update set name = excluded.name, team_code = excluded.team_code;

insert into settings (id, config) values (1, ${q(JSON.stringify(DEFAULT_SETTINGS))}::jsonb)
on conflict (id) do nothing;

insert into results (id, data) values (1, '{"champion":null,"runnerUp":null,"goldenBoot":null,"latamFurthest":null,"darkHorseTeam":null,"stageReached":{}}'::jsonb)
on conflict (id) do nothing;
`;

const out = path.join(process.cwd(), "supabase", "seed.sql");
writeFileSync(out, sql, "utf8");
console.log(`Wrote ${out} (${TEAMS.length} teams, ${PLAYERS.length} players)`);
